@startuml
left to right direction
:Guffe: as pt
:Doctor: as dc
:Nurse: as nr

rectangle KOLNET {
(Prescription) as ps
(Create online consultation) as ca
(Attend online consultation) as aa
(View report) as VR
(Write report) as ER
(Submit PROM) as S.PROM
(View PROM) as V.PROM

pt - S.PROM #line:red
pt -- V.PROM #line:red
pt -- aa #line:red
pt -- VR #line:red
dc -- V.PROM #line:blue
dc -- ps #line:blue
dc -- ER #line:blue
dc -- ca #line:blue
dc -- aa #line:blue
V.PROM -- nr
VR -- nr
aa -- nr
aa <. ca : extend
S.PROM .> V.PROM :extend
ER <. aa :include
}




@enduml