# Form implementation generated from reading ui file 'login_widget.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
import sqlite3
import sys
import os
import time
import mysql.connector
from PyQt6 import QtCore, QtWidgets
from PyQt6.uic import loadUi
from PyQt6.QtWidgets import QDialog, QApplication, QWidget, QLineEdit, QPushButton, QLabel, QGridLayout, QSizePolicy
from PyQt6.QtSql import QSqlDatabase, QSqlQuery

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(378, 233)
        self.cpr_input = QtWidgets.QLineEdit(parent=Form)
        self.cpr_input.setGeometry(QtCore.QRect(100, 80, 181, 21))
        self.cpr_input.setText("")
        self.cpr_input.setObjectName("cpr_input")
        self.searchbutton = QtWidgets.QPushButton(parent=Form)
        self.searchbutton.setGeometry(QtCore.QRect(130, 120, 113, 32))
        self.searchbutton.setObjectName("searchbutton")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(120, 50, 141, 21))
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.searchbutton.setText(_translate("Form", "Search"))
        self.label.setText(_translate("Form", "Social security number"))

#Opretter fobindelse til DB
mydb = mysql.connector.connect(host="localhost", user="root", password="Gulerodskage64", database="patient_liste")

#Vælger patient table
mycursor = mydb.cursor()
mycursor.execute("Select * from patient")
myresult = mycursor.fetchall()

#Print patientlisten fra DB
for row in myresult:
    print(row)

## Forbind input til database
# https://www.youtube.com/watch?v=RL9nGmv3uSU&t=21s

class Login(QDialog):
    def __init__(self):
        super(Login, self).__init__()
        loadUi("login.ui", self)
        self.searchbutton.clicked.connect(self.loginfunction)
        self.cpr_input.setEchoMode(QtWidgets.QLineEdit.cpr_input)
    def loginfunction(self):
        cpr = self.cpr_input.text()
        print("Successfully logged in")

class menu(QDialog):
    def __init__(self):
        super(menu, self).__init__()
        loadUi("main_widget.ui", self)
        self.searchbutton.clicked.connect(self.loginfunction)
        self.cpr_input.setEchoMode(QtWidgets.QLineEdit.cpr)
    def loginfunction(self, widget="main_widget.ui"):
        cpr = self.cpr_input.text()
        if self.cpr.text() == self.mydbcursor:
            widget.addWidget(Login)



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())