# Form implementation generated from reading ui file 'create_user_widget.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt6 import QtCore, QtGui, QtWidgets
from SQL_connector import createUser
from PyQt6.QtWidgets import QMessageBox, QLabel

class Ui_create_user_menu(object):
    def setupUi(self, create_user_menu):
        create_user_menu.setObjectName("create_user_menu")
        create_user_menu.resize(411, 381)
        self.formLayoutWidget = QtWidgets.QWidget(parent=create_user_menu)
        self.formLayoutWidget.setGeometry(QtCore.QRect(60, 70, 291, 241))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.cpr_create = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.cpr_create.setText("")
        self.cpr_create.setObjectName("cpr_create")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.cpr_create)
        self.label_5 = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_5)
        self.name_create = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.name_create.setText("")
        self.name_create.setObjectName("name_create")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.name_create)
        self.label_4 = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_4)
        self.telephone_create = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.telephone_create.setText("")
        self.telephone_create.setObjectName("telephone_create")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.telephone_create)
        self.label_2 = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.age_create = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.age_create.setObjectName("age_create")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.age_create)
        self.label_6 = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_6)
        self.weight_create = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.weight_create.setObjectName("weight_create")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.weight_create)
        self.label_7 = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_7.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_7)
        self.fev1_create = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.fev1_create.setObjectName("fev1_create")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.FieldRole, self.fev1_create)
        self.label_3 = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_3)
        self.gold_create = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.gold_create.setObjectName("gold_create")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.ItemRole.FieldRole, self.gold_create)
        self.label_8 = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_8.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_8)
        self.mrc_create = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.mrc_create.setObjectName("mrc_create")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.ItemRole.FieldRole, self.mrc_create)
        self.create_user_button = QtWidgets.QPushButton(parent=create_user_menu)
        self.create_user_button.setGeometry(QtCore.QRect(210, 330, 113, 32))
        self.create_user_button.setObjectName("create_user_button")
        self.label_9 = QtWidgets.QLabel(parent=create_user_menu)
        self.label_9.setGeometry(QtCore.QRect(130, 20, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")

        self.message_label = QLabel('', create_user_menu)
        self.message_label.move(20, 240)
        self.message_label.resize(360, 25)


        self.retranslateUi(create_user_menu)
        QtCore.QMetaObject.connectSlotsByName(create_user_menu)

    def retranslateUi(self, create_user_menu):
        _translate = QtCore.QCoreApplication.translate
        create_user_menu.setWindowTitle(_translate("create_user_menu", "Form"))
        self.label.setText(_translate("create_user_menu", "cpr"))
        self.label_5.setText(_translate("create_user_menu", "name"))
        self.label_4.setText(_translate("create_user_menu", "telephone number"))
        self.label_2.setText(_translate("create_user_menu", "age"))
        self.label_6.setText(_translate("create_user_menu", "weight"))
        self.label_7.setText(_translate("create_user_menu", "FEV1"))
        self.label_3.setText(_translate("create_user_menu", "GOLD"))
        self.label_8.setText(_translate("create_user_menu", "MRC"))
        self.create_user_button.setText(_translate("create_user_menu", "Create user"))
        self.label_9.setText(_translate("create_user_menu", "Create User"))

        self.create_user_button.clicked.connect(self.createuserLocal)

    def createuserLocal(self):
        cpr = self.cpr_create.text()
        name = self.name_create.text()
        telephone = self.telephone_create.text()
        age = self.age_create.text()
        weight = self.weight_create.text()
        fev1 = self.fev1_create.text()
        GOLD = self.gold_create.text()
        MRC = self.mrc_create.text()

        if not cpr or not name or not telephone or not age or not weight or not fev1 or not GOLD or not MRC:
            QMessageBox.warning(
                QtWidgets.QWidget(),
                'Error',
                'Please fill out all fields'
            )
            return

        else:
            createUser(cpr, name, telephone, age, weight, fev1, GOLD, MRC)
            self.cpr_create.setText('')
            self.name_create.setText('')
            self.telephone_create.setText('')
            self.age_create.setText('')
            self.weight_create.setText('')
            self.fev1_create.setText('')
            self.gold_create.setText('')
            self.mrc_create.setText('')
            QMessageBox.information(
                create_user_menu,
                'Success',
                'User created successfully!',
                QMessageBox.StandardButton.Ok
            )





if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    create_user_menu = QtWidgets.QWidget()
    ui = Ui_create_user_menu()
    ui.setupUi(create_user_menu)
    create_user_menu.show()
    sys.exit(app.exec())
