# Form implementation generated from reading ui file 'main3_widget.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt6 import QtCore, QtGui, QtWidgets
from SQL_connector import select

#from prom_widget import Ui_PromView

class MainWindow(object):
    def setupUi(self, Form, cpr):
        Form.setObjectName("Form")
        Form.resize(510, 500)
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(60, 150, 160, 301))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cpr = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.cpr.setObjectName("cpr")
        self.verticalLayout.addWidget(self.cpr)
        self.name = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.name.setObjectName("name")
        self.verticalLayout.addWidget(self.name)
        self.age = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.age.setObjectName("age")
        self.verticalLayout.addWidget(self.age)
        self.telephone = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.telephone.setObjectName("telephone")
        self.verticalLayout.addWidget(self.telephone)
        self.weight = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.weight.setObjectName("weight")
        self.verticalLayout.addWidget(self.weight)
        self.fev1 = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.fev1.setObjectName("fev1")
        self.verticalLayout.addWidget(self.fev1)
        self.gold = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.gold.setObjectName("gold")
        self.verticalLayout.addWidget(self.gold)
        self.mrc = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.mrc.setObjectName("mrc")
        self.verticalLayout.addWidget(self.mrc)
        self.gridLayoutWidget = QtWidgets.QWidget(parent=Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(290, 150, 181, 301))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.consultationbutton = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.consultationbutton.setFont(font)
        self.consultationbutton.setObjectName("consultationbutton")
        self.gridLayout.addWidget(self.consultationbutton, 4, 0, 1, 1)
        self.reportbutton = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.reportbutton.setFont(font)
        self.reportbutton.setObjectName("reportbutton")
        self.gridLayout.addWidget(self.reportbutton, 2, 0, 1, 1)
        self.prescriptionbutton = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.prescriptionbutton.setFont(font)
        self.prescriptionbutton.setObjectName("prescriptionbutton")
        self.gridLayout.addWidget(self.prescriptionbutton, 3, 0, 1, 1)
        self.prombutton = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.prombutton.setFont(font)
        self.prombutton.setObjectName("prombutton")
        self.gridLayout.addWidget(self.prombutton, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(100, 40, 81, 81))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/newPrefix/blank-profile-picture-973460_960_720 kopi.png"))
        self.label.setObjectName("label")

        self.retranslateUi(Form, cpr)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form, cpr):

        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Patient Menu"))
        self.cpr.setText(_translate("Form", f"CPR: {select('cpr', 'Patients', 'cpr', str(cpr))[0][0]}"))
        self.name.setText(_translate("Form", f"Name: {select('name', 'Person', 'cpr', str(cpr))[0][0]}"))
        self.age.setText(_translate("Form", f"Age: {select('age', 'Person', 'cpr', str(cpr))[0][0]}"))
        self.telephone.setText(_translate("Form", f"Telephone: {select('telephone', 'Person', 'cpr', str(cpr))[0][0]} "))
        self.weight.setText(_translate("Form", f"Weight: {select('Weight', 'Patients', 'cpr', str(cpr))[0][0]}"))
        self.fev1.setText(_translate("Form", f"FEV1: {select('fev1', 'Patients', 'cpr', str(cpr))[0][0]}"))
        self.gold.setText(_translate("Form", f"GOLD: {select('GOLD', 'Patients', 'cpr', str(cpr))[0][0]}"))
        self.mrc.setText(_translate("Form", f"MRC: {select('MRC', 'Patients', 'cpr', str(cpr))[0][0]}"))
        self.consultationbutton.setText(_translate("Form", "Create consultation"))
        self.reportbutton.setText(_translate("Form", "Write Report"))
        self.prescriptionbutton.setText(_translate("Form", "Create prescription"))
        self.prombutton.setText(_translate("Form", "PROM"))
        # INDSAT
        #self.prombutton.clicked.connect(self.prombutton_clicked)

        #INDSAT

        #def prombutton_clicked(self):
        #    self.prom_widget = QtWidgets.QWidget()
        #    self.ui2 = Ui_PromView()
        #    self.ui2.setupUi(self.prom_widget)
        #    self.prom_widget.show()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = MainWindow()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
