@startuml
'https://plantuml.com/class-diagram
title Class Diagram: KOLNET

class "Persons" as persons{
name: string
age: int
address: string
phone number: int
social security number: int
}

class "PROM" as prom {
FEV1: float
saturation: int
pulse: int
mucos: bool
health questions: bool
}

class "Patient" as patient{
relatives: string
mrc: int
weight: int
fev1: int
gold: int
+id: int
}

class "Doctor" as doctor

class "Nurse" as nurse

class "Health professional" as HP {
speciality: string
profession ID: string
work ID: int
department: string
}

interface "Main Window" as MW {
Create user()
Edit user()
Delete user()
}

class "Login" as login{
user_id: string
password: string
Deny Access()
Grant Access()
}


class "Look up user" as LU
LU : Create consultation()
LU : Create prescription()
LU : Write report()
LU : View Prom()

package Database <<Database>> {
class "DB" as db_hp
}
db_hp : Patients: table
db_hp : Person: table
db_hp : testresults: table
db_hp : Health Professionals: table
db_hp : PROM: schema
db_hp : connect()



persons "1..1  "<|- HP
persons "1..1  "<|-- "1..1  "patient
HP "1..1    "  <|-- "1..1    "doctor
HP "  1..1    "  <|-- "1..1    " nurse
doctor " 1..* "--> "1..1" login
nurse " 1..*"--> " 1..1" login
patient " 1..*"--> "1..1  " login
login -->  MW
MW -> LU
MW --> db_hp
MW --> prom
login -> db_hp
LU --> prom
db_hp <- LU
prom ----> db_hp

@enduml