@startuml
'https://plantuml.com/class-diagram

class "Persons" as persons
persons : name: string
persons : age: int
persons : address: string
persons : phone number: int
persons : social security number: int

class "PROM" as prom
prom : FEV1: float
prom : saturation: int
prom : pulse: int
prom : subjective health questions: bool

class "Patient" as patient
patient : relatives: string

class "Doctor" as doctor

class "Nurse" as nurse

class "Health professional" as HP
HP : speciality: string
HP : profession ID: string
HP : work ID: int
HP : department: string

class "Main Window" as MW
MW : Create prescription ()
MW : Write report()
MW : Create consultation()

class "Login" as login

class "Database" as db
db : Deny Access()
db : Grant Access()

persons <|- HP
persons <|-- patient
HP <|-- doctor
HP <|-- nurse
doctor "1"--> login
nurse "1" --> login
prom --* MW
db . (login,MW)
db -- MW
prom - db

patient "1..1  " <|-- "0..* " prom
@enduml