@startuml
'https://plantuml.com/class-diagram

class "Persons" as persons
persons : name: string
persons : age: int
persons : address: string
persons : phone number: int
persons : social security number: int

class "PROM" as prom
prom : FEV1: float
prom : saturation: int
prom : pulse: int
prom : subjective health questions: bool

class "Create Consultation" as consultation
consultation : date: int
consultation : contact information: string

class "Patient" as patient
patient : relatives: string

class "Doctor" as doctor

class "Nurse" as nurse

class "Write Report" as WR
WR : medical history: string
WR : prescriptions: string

class "Health professional" as HP
HP : speciality: string
HP : profession ID: string
HP : work ID: int
HP : department: string

class "Main Window" as MW

class "Create prescription" as CP

class "Login" as login

persons <|-- HP
persons <|-- patient
HP <|-- doctor
HP <|-- nurse
doctor "1"--> login
nurse "1" --> login
prom --* MW
consultation --*MW
CP --* MW
WR --* MW
login --> MW
patient <|-- prom
@enduml